spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
server:
  port: 8001




error:
  whitelabel:
    enabled: false